---
version: "3.9"

volumes:
  ovos_models:
    name: ovos_models
    driver: local
  ovos_vosk:
    name: ovos_vosk
    driver: local
  ovos_listener_records:
    name: ovos_listener_records
    driver: local

services:
  ovos_messagebus:
    container_name: ovos_messagebus
    hostname: ovos_messagebus
    restart: unless-stopped
    image: smartgic/ovos-messagebus:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft

  ########################
  # Uncomment this service if you want to use the C++ implementation
  # of the message bus.
  ########################
  # ovos_messagebus:
  #   container_name: ovos_messagebus
  #   hostname: ovos_messagebus
  #   restart: unless-stopped
  #   image: smartgic/ovos-bus-server:${VERSION}
  #   pull_policy: always
  #   environment:
  #     TZ: $TZ
  #   network_mode: host
  #   ipc: host
  #   volumes:
  #     - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
  #     - ${TMP_FOLDER}:/tmp/mycroft

  ovos_gui_websocket:
    container_name: ovos_gui_websocket
    hostname: ovos_gui_websocket
    restart: unless-stopped
    image: smartgic/ovos-gui-websocket:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
    depends_on:
      - ovos_messagebus

  ovos_phal:
    container_name: ovos_phal
    hostname: ovos_phal
    restart: unless-stopped
    image: smartgic/ovos-phal:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus

  ovos_phal_admin:
    container_name: ovos_phal_admin
    hostname: ovos_phal_admin
    restart: unless-stopped
    image: smartgic/ovos-phal-admin:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    privileged: true
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${TMP_FOLDER}:/tmp/mycroft
      - /sys:/sys:ro
      - /dev:/dev:ro
    depends_on:
      - ovos_messagebus

  ovos_listener:
    container_name: ovos_listener
    hostname: ovos_listener
    restart: unless-stopped
    image: smartgic/ovos-listener:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ovos_listener_records:/home/${OVOS_USER}/.local/share/mycroft/listener
      - ovos_models:/home/${OVOS_USER}/.local/share/precise-lite
      - ovos_vosk:/home/${OVOS_USER}/.local/share/vosk
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus
      - ovos_phal

  ########################
  # Uncomment this service if you want to use the Dinkum listener
  ########################
  # ovos_listener:
  #   container_name: ovos_listener
  #   hostname: ovos_listener
  #   restart: unless-stopped
  #   image: smartgic/ovos-listener-dinkum:${VERSION}
  #   pull_policy: always
  #   environment:
  #     PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
  #     PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
  #     TZ: $TZ
  #   network_mode: host
  #   ipc: host
  #   devices:
  #     - /dev/snd
  #   volumes:
  #     - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
  #     - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
  #     - ovos_listener_records:/home/${OVOS_USER}/.local/share/mycroft/listener
  #     - ovos_models:/home/${OVOS_USER}/.local/share/precise-lite
  #     - ovos_vosk:/home/${OVOS_USER}/.local/share/vosk
  #     - ${TMP_FOLDER}:/tmp/mycroft
  #     - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
  #   depends_on:
  #     - ovos_messagebus
  #     - ovos_phal

  ovos_audio:
    container_name: ovos_audio
    hostname: ovos_audio
    restart: unless-stopped
    image: smartgic/ovos-audio:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus
      - ovos_phal

  ovos_core:
    container_name: ovos_core
    hostname: ovos_core
    restart: unless-stopped
    image: smartgic/ovos-core:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
    network_mode: host
    ipc: host
    devices:
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
    depends_on:
      - ovos_messagebus
      - ovos_phal

  ovos_gui:
    container_name: ovos_gui
    hostname: ovos_gui
    restart: unless-stopped
    image: smartgic/ovos-gui:${VERSION}
    pull_policy: always
    environment:
      PULSE_SERVER: unix:${XDG_RUNTIME_DIR}/pulse/native
      PULSE_COOKIE: /home/${OVOS_USER}/.config/pulse/cookie
      TZ: $TZ
      DISPLAY: :0
      QT_QPA_PLATFORM: eglfs
    network_mode: host
    ipc: host
    devices:
      - /dev/dri
      - /dev/snd
    volumes:
      - ~/.config/pulse/cookie:/home/${OVOS_USER}/.config/pulse/cookie:ro
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft:ro
      - ${TMP_FOLDER}:/tmp/mycroft
      - ${XDG_RUNTIME_DIR}:${XDG_RUNTIME_DIR}:ro
      - ${XDG_RUNTIME_DIR}/pulse:${XDG_RUNTIME_DIR}/pulse:ro
      - ${SHARE_FOLDER}:/home/${OVOS_USER}/.local/share/mycroft
    depends_on:
      - ovos_messagebus
      - ovos_gui_websocket
      - ovos_phal

  ovos_cli:
    container_name: ovos_cli
    hostname: ovos_cli
    restart: unless-stopped
    image: smartgic/ovos-cli:${VERSION}
    pull_policy: always
    environment:
      TZ: $TZ
    network_mode: host
    ipc: host
    volumes:
      - ${CONFIG_FOLDER}:/home/${OVOS_USER}/.config/mycroft
      - ${TMP_FOLDER}:/tmp/mycroft
